# Generated by Django 3.1.5 on 2021-05-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='a19plspgtos',
            name='descricaoexterna',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
